services:
  # Tempo and Loki runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  init:
    image: busybox
    user: root
    entrypoint: ["/bin/sh", "-c"]
    command: 
    - |
      chown 10001:10001 /data/tempo
      chown 10001:10001 /data/loki
    volumes:
      - tempo_data:/data/tempo
      - loki_data:/data/loki

  tempo:
    image: grafana/tempo:2.7.1
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo.yml:/etc/tempo.yml
      - tempo_data:/data/tempo
    ports:
      - 3200:3200 # tempo
      - 4417:4417 # otlp grpc
      - 4418:4418 # otlp http
    depends_on:
      - init
    restart: unless-stopped

  loki:
    image: grafana/loki:3.4.2
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    volumes:
      - loki_data:/data/loki
      - ./loki-config.yml:/etc/loki/local-config.yaml:ro
    ports:
      - "3100:3100"
    depends_on:
      - init
    restart: unless-stopped
      
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
      - '--web.enable-otlp-receiver'
      - '--enable-feature=exemplar-storage'
      - '--enable-feature=native-histograms'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped
      
  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana_data:/var/lib/grafana/
      - ./ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml
      - ./dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus
      - tempo
      - loki
  
  otel-collector:
    container_name: otelcollector
    image: otel/opentelemetry-collector-contrib:0.103.0
    command: [ --config=/etc/otel-collector-config.yml ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    depends_on:
      - prometheus
      - loki
      - tempo
    ports:
      #   - 1888:1888 # pprof extension
      #   - 8888:8888 # Prometheus metrics exposed by the collector
      #   - 8889:8889 # Prometheus exporter metrics
      #   - 13133:13133 # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    #   - 55679:55679 # zpages extension
    restart: unless-stopped
    
volumes:
  grafana_data:
  loki_data:
  prometheus_data:
  tempo_data: