receivers:
  otlp:
    protocols:
      http: null
      grpc:

        null
processors:
  resource:
    attributes:
      # - action: insert
      # key: loki.format
      # value: raw
      - action: insert
        key: loki.resource.labels
        value: app, runtime
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  prometheus:
    # metrics
    endpoint: otelcollector:8889
    namespace: demo
    send_timestamps: true
    resource_to_telemetry_conversion:
      enabled: true
    const_labels:
      exported: collector

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
      # otlp/jaeger:
      # protocols:
      # grpc:
      # endpoint: "http://jaeger:14250"
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans

service:
  pipelines:

    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - prometheus

    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp
        - zipkin

    logs:
      receivers:
        - otlp
      processors:
        - batch
        - resource
      exporters:
        - loki