{
 "title": "ASP.NET OpenTelemetry dotnet webapi",
 "description": "OpenTelemetry .Net (dotnet) ASP.NET using RED and USE method",
 "tags": [
  "loki",
  "mimir",
  "otlp",
  "opentelemetry",
  "asp.net",
  "dotnet"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prom_ds", "query": "prometheus" },
   { "name": "loki_ds", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(dotnet_assembly_count,job)"
    }
   },
   {
    "name": "service_version",
    "label": "Service version",
    "query": {
     "query": "label_values(dotnet_assembly_count{job=\"$job\"},service_version)"
    }
   },
   {
    "name": "http_route",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=\"$job\", service_version=\"$service_version\"},http_route)"
    }
   },
   {
    "name": "metric_filter",
    "label": "Metric Filter",
    "query": "job=\"$job\", service_version=\"$service_version\", http_route=~\"${http_route}\""
   },
   { "name": "top", "label": "Top", "query": "1, 5, 10" },
   { "name": "percentile", "query": "p95 : 0.95, p50 : 0.50" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rates",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(${top}, \r\n    sum by (http_response_status_code) (rate(http_server_request_duration_seconds_count{$metric_filter}[$__rate_interval]))\r\n)",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "heatmap",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-httpserverrequestduration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{$metric_filter}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Http Server requests Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(${top}, \r\n    sum by (host_name,http_request_method,http_route,url_scheme,http_response_status_code) (rate(http_server_request_duration_seconds_count{$metric_filter}[$__rate_interval]))\r\n)",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{host_name}}{{http_route}}: {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Http Server requests Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(${top}, \r\n    sum by(host_name, url_scheme, http_request_method, http_route, http_response_status_code, error_type) (rate(http_server_request_duration_seconds_count{$metric_filter, http_response_status_code!~\"[1-3]..\"}[$__rate_interval]))\r\n)",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{host_name}}{{http_route}}: {{http_response_status_code}} {{error_type}}"
    }
   ]
  },
  {
   "title": "Http Server requests Durations ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top, \r\n    histogram_quantile(${percentile:value}, \r\n        sum(rate(http_server_request_duration_seconds_bucket{$metric_filter}[$__rate_interval])) by (le, http_request_method, url_scheme, host_name, http_route, http_response_status_code)\r\n    )\r\n)",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{host_name}}{{http_route}}: {{http_response_status_code}}"
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "In-flight HTTP requests",
   "type": "timeseries",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-httpserveractive_requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (host_name, http_request_method, url_scheme) (rate(http_server_active_requests{$metric_filter}[$__rate_interval]))",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{host_name}}"
    }
   ]
  },
  {
   "title": "Routing match attempts",
   "type": "timeseries",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-aspnetcoreroutingmatch_attempts",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (host_name,http_route,aspnetcore_routing_is_fallback) (rate(aspnetcore_routing_match_attempts_total{$metric_filter, aspnetcore_routing_match_status!=\"success\" }[$__rate_interval]))",
     "legendFormat": "{{host_name}}{{http_route}} failure (fallback:{{aspnetcore_routing_is_fallback}})"
    },
    {
     "expr": "sum by (instance,http_route) (rate(aspnetcore_routing_match_attempts_total{$metric_filter, aspnetcore_routing_match_status=\"success\", aspnetcore_routing_is_fallback=\"true\" }[$__rate_interval]))",
     "legendFormat": "{{host_name}}{{http_route}} fallback route"
    },
    {
     "expr": "sum by (host_name,http_route) (rate(aspnetcore_routing_match_attempts_total{$metric_filter, aspnetcore_routing_match_status=\"success\", aspnetcore_routing_is_fallback=\"false\" }[$__rate_interval]))",
     "legendFormat": "{{host_name}}{{http_route}} success"
    }
   ]
  },
  {
   "title": "Active connections (kestrel)",
   "type": "timeseries",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-kestrelactive_connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(kestrel_active_connections{$metric_filter}[$__interval])",
     "legendFormat": "{{network_type}} {{network_transport}} {{server_address}}:{{server_port}}"
    }
   ]
  },
  {
   "title": "Queued connections (kestrel)",
   "type": "timeseries",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-kestrelqueued_connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(kestrel_queued_connections{$metric_filter}[$__interval])",
     "legendFormat": "{{network_type}} {{network_transport}} {{server_address}}:{{server_port}}"
    }
   ]
  },
  {
   "title": "Connections Durations ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top, \r\n    histogram_quantile(${percentile:value}, \r\n        sum(rate(kestrel_connection_duration_seconds_bucket{$metric_filter}[$__rate_interval])) by (le,network_protocol_name,network_protocol_version,network_transport,network_type,server_address,server_port)\r\n    )\r\n)",
     "legendFormat": "{{network_type}} {{network_transport}}/{{network_protocol_name}}{{network_protocol_version}} {{server_address}}:{{server_port}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_time_seconds_total{$metric_filter }[$__rate_interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_memory_usage_bytes{$metric_filter}[$__rate_interval])",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Process Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_thread_count{$metric_filter}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "GC Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(dotnet_gc_last_collection_memory_committed_size_bytes{$metric_filter}[$__rate_interval])",
     "legendFormat": "GC Commited Memory Size"
    },
    {
     "expr": "rate(dotnet_gc_heap_allocated_bytes_total{$metric_filter}[$__rate_interval])",
     "legendFormat": "GC Allocation Size"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(dotnet_gc_heap_allocated_bytes_total{$metric_filter}[$__rate_interval])",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Heap Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(dotnet_gc_last_collection_heap_fragmentation_size_bytes{$metric_filter}[$__rate_interval])",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (gc_heap_generation, instance) (rate (dotnet_gc_collections_total{$metric_filter}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (error_type, instance) (rate(dotnet_exceptions_total{$metric_filter}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Pool Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(dotnet_thread_pool_thread_count_total{$metric_filter}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thread Pool Queue Length",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(dotnet_thread_pool_queue_length_total{$metric_filter}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "HTTP Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Open connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(http_client_open_connections{$metric_filter}[$__interval])",
     "legendFormat": "{{instance}} {{http_connection_state}} {{server_address}}:{{server_port}} {{url_scheme}}{{network_protocol_version}}"
    }
   ]
  },
  {
   "title": "Http Client requests Durations ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top, \r\n    histogram_quantile(${percentile:value}, \r\n        sum(rate(http_client_request_duration_seconds_bucket{$metric_filter}[$__rate_interval])) by (le, http_request_method, url_scheme, http_route, http_response_status_code,server_address,server_port,network_protocol_version)\r\n    )\r\n)",
     "legendFormat": " {{instance}} {{url_scheme}}/{{network_protocol_version}} {{server_address}}:{{server_port}} {{http_request_method}}: {{http_response_status_code}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$job\"} |= ``",
     "maxLines": 100
    }
   ]
  }
 ]
}